version: '3'

services:
  angular-app:
    build:
      context: .
    volumes:
      - ./apps:/home/node/apps
    working_dir: /home/node/apps/MY-APP
    ports:
      - "4200:4200"
    command: ["/bin/bash","-c","cd .. && ng new MY-APP --skip-git"]
